spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://mysql-22d64e89-alpha-storage.i.aivencloud.com:26301/alphastorage
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_ka80a83MkwPF4Fd3hxV

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# spring.jpa.show-sql: true
#config spring security
spring.security.user.name=anpha
spring.security.user.password=123456
#config viewengine
# spring.profiles.active=prod
# spring.mvc.view.prefix=/WEB-INF/view/
# spring.mvc.view.suffix=.jsp
minio.access_key=29SQNS6IbTwJLGZRYD7Q