jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600000 # in second
  refreshable-duration: 3600000 # in seconds
minio:
  url: http://localhost:9000
  access_key: pibxclsPJjhMTzfTblYg
  secret_key: KelFAOe0ZVANmG7HFs7KX11E71QLMFUq6LyLErhM
  urlDuration: 10

version:
  numOfVersion: 2
