server:
  port: ${SERVER_PORT:8080} 

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://smartprintproject-hothanhnha25062004-0ace.h.aivencloud.com:19349/storage}
    username: ${SPRING_DATASOURCE_USERNAME:avnadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:AVNS_0ZapZiAKfvz3wzVZH9v}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:anpha}
      password: ${SPRING_SECURITY_USER_PASSWORD:123456}

jwt:
  signerKey: ${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}
  valid-duration: ${JWT_VALID_DURATION:3600000} # in seconds
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:3600000} # in seconds

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access_key: ${MINIO_ACCESS_KEY:gn2yqUPVBzolaPpoa7jP}
  secret_key: ${MINIO_SECRET_KEY:PcUjUbumsycnsrqKJ9fOsKSNLBcqnelk7DfMukIn}
  urlDuration: ${MINIO_URL_DURATION:10}
  host: ${MINIO_HOST:http://14.225.241.238/minio}

version:
  numOfVersion: ${VERSION_NUM_OF_VERSION:2}

env: ${SPRING_ENV:dev}
